import { environment } from "src/environments/environment"

export const Configuration = {
  languages: ['ar', 'en'],
  defaultLang: 'ar',
  secretKey: 'NewTripsKey',
  APIs: {
    account: {
      login: '/api/Token/Authenticate',
      RefreshToken: '/api/Token/RefreshToken',
      GetRoles: '/api/Token/GetRoles?RoleId=',
      CheckDongle: '/api/Token/CheckDongle?request=',
    },
    Clients:
    {
      ClientMangment: '/api/Client/GetClientMangment?filter=',
      new_cleint: '/api/Client/CreateClient',
      new_cleintFromVlense: '/api/Client/CreateClientFromVlense',
      GetClientCreditStatus: '/api/Client/GetClientCreditStatus?RelationCode=',
      CreateCreditlmit: '/api/Client/CreateCreditlmit',
      ListOfCreditLimit: '/api/Client/ListCreditlmit',
      searchClients: '/api/Client/list',
      Update_cleint: '/api/Client/UpdateClient',
      FamliyMember: '/api/Client/AddFamily',
      get_cleint: '/api/Client/getmainClient?RelationCode=',
      Setting: '/api/Client/ClientSetting?relatiocode=',
      SubSetting: '/api/Client/GetSubProperties?relationCode=',
      UpdateSubSetting: '/api/Client/UpdateSubProperties',
      UpdateTradeSetting: '/api/Client/UpdateTradeSetting',
      UpdateTrackSetting: '/api/Client/UpdateTrackSetting',
      updateClientonline: '/api/Client/UpdateClientonline',
      insertOrUpdateClientSubscribe: '/api/Client/InsertOrUpdateClientSubscribe',
      getClientSubScribe: '/api/Client/getClientSubScribe?relatiocode=',
      deleteClientSubscribe: '/api/Client/deleteClientSubscribe?id=',
      addClientCustodians: '/api/Client/CreateOrUpdateClientCustodians',
      getClientCustodians: '/api/Client/GetClientCustodians?relationcode=',
      GetComapnyCustodian: '/api/Client/CompanyCustodian?id=0',
      deleteClientCustodian: '/api/Client/deleteClientCustodian?ID=',
      GetMasterCommisionList: '/api/Client/GetMasterCommisionList?RelatioCode=',
      GetClientCommisionList: '/api/Client/GetClientCommisionList?',
      CreateClientCommission: '/api/Client/CreateClientCommission',
      updateClientCommission: '/api/client/updateClientCommission',
      deleteClientCommission: '/api/Client/deleteClientCommission?groupingId=',
      getArchivesByClient: '/api/Client/GetArchivesByClient?relationCode=',
      getArchivesByType: '/api/Client/GetArchivesByType',
      deleteArchive: '/api/Client/DeleteArchive?ID=',
      createOrUpdateArchive: '/api/Client/CreateOrUpdateArchive',
      CreateClientCustCommission: '/api/Client/CreateClientCustCommission',
      updateClientCustCommission: '/api/client/updateClientCustCommission',
      deleteClientCustCommission: '/api/Client/deleteClientCustCommission?groupingId=',
      getlistClientCustCommission: '/api/Client/GetClientCommisionCustList?',
      CheckPostingCustodaionCommission: '/api/Client/CheckCustPostingCommission?RelationCode=',
      CheckPostingCommission: '/api/Client/CheckPostingCommission?RelationCode=',
      CreatePOA: '/api/Client/CreatePOA',
      deletePOA: '/api/Client/deletePOA?id=',
      deleteMinor: '/api/Client/deleteMinor?RelationCode=',
      AddPersonalAccount: '/api/Client/CreatePersonalAccount',
      CreateSub: '/api/Client/CreateSub',
      AddExistingSub: '/api/Client/AddExistingSub',
      SuspendRelation: '/api/Client/SuspendRelation?RelationCode=',
      ResetCredentials: '/api/Client/ResetCredentials',
      GetClientMargin: '/api/Client/GetClientMargin?RelationCode=',
      GetMarginCategoryByID: '/api/Client/GetMarginCategoryByID?id=',
      SavePrivateMarginCategory: '/api/Client/SaveMarginCategory',
      SavePublicMarginCategory: '/api/Client/UpdatedClientMarginCategory',
      GetClientPrivateMarginCategory: '/api/Client/GetClientPrivateMarginCategory?MarginCategoryID=',
      getClientProfileMainData: '/api/Client/Profile?relationCode=',
      getClientPrtofolio: '/api/Client/Protofolio?relationCode=',
      GetClientOrders: '/api/Client/GetClientOrders?filter=',
      GetRequiredInvestment: '/api/Client/GetRequiredInvestment?filter=',
      GetClientTransaction: '/api/Client/GetClientTransaction?filter=',
      GetOrderHist: '/api/Client/GetOrderHist?OrderNumber=',
      CreateExternalEinvoiceClient: '/api/Client/CreateExternalEinvoiceClient',
      CreateExternalEinvoice: '/api/Client/CreateExternalEinvoice',
      DeleteExternalInvoice: '/api/Client/DeleteExternalEinvoice?id=',
      GetExternalClients: '/api/Client/GetExternalClients?filter=',
      DeleteInvoiceClient: '/api/Client/DeleteExternalEinvoiceClient?id=',
      GetManualInvoices: '/api/Client/GetManualInvoices?filter=',
      GetOnlineClient: '/api/Client/GetOnlineClient?filter=',
      GetOnlineClientCounts: '/api/Client/GetOnlineClientCounts?filter=0',
      GetExternalClientsByName: '/api/Client/GetExternalClientsByName?filter=',
      PostInvoiceCommission: '/api/Client/PostInvoiceCommission',
      GetClientOverview: '/api/Client/GetWidget1?filter=',
      GetClientDistribution: '/api/Client/GetWidget2?filter=',
      GetClientStatistics: '/api/Client/GetWidget4?filter=',
      GetRecentCustomers: '/api/Client/GetWidget3?filter=',
      GetClientCreationDetails: '/api/Client/GetClientCreationDetails?filter=',
      GetPendingVLenseRequests: '/api/Client/GetPendingClientVLenseRequests?filter=',
      RevokeVLenseRequest: '/api/Client/RevokeVLenseRequest',
      GetVLenseRequests: '/api/Client/GetVLenseRequestsByFilter?filter=',
      GetVLenseClientByID: '/api/Client/GetVLenseClientByID?id=',
      GetVLenseRequestsCount: '/api/Client/GetPendingVLenseRequestsCount?filter=',
      AddRequestComment: '/api/Client/AddRequestComment',
      GetVLenseImagesByID: '/api/Client/GetVLenseImagesByID?id=',
      GetActiveClientTradingInfo: '/api/Client/GetActiveClientTradingInfo',
      SubmitClientGroup: '/api/Client/SubmitClientGroup',
      UpdateClientGroup: '/api/Client/UpdateClientGroup',
      GetClientGroupInfo: '/api/Client/GetClientGroupInfo/',
      GetRelations: '/api/Client/GetRelations'
    },
    Operations: {
      GetDormantClients: '/api/Operation/ListClientDormantStatus?request=',
      ChangeClientDormantStatus: '/api/Operation/UpdateClientDormantStatus',
      GetRecentDormants: '/api/Operation/GetRecentDormantClients?isDormant='
    },
    Margin: {
      GetCreditLimitSummary: '/api/margin/GetCreditLimitSummary',
      GetMarginSummary: '/api/margin/GetMarginSummary',
      SaveMarginCategory: '/api/margin/SaveMarginCategory',
      GetStatisticsMarginOrders: '/api/margin/GetStatisticsMarginOrders',
      GetMarginOrders: '/api/margin/GetMarginOrders?filter=',
      GetMarginSymbols: '/api/Settings/GetMarginSymbols?filter=',
      UpdateMarginSymbolsInfo: '/api/margin/UpdateMarginSymbolsInfo',
      GetClientMarginSummary: '/api/margin/GetClientMarginSummary',
      GetMarginInfo: '/api/margin/GetMarginInfo',
      SaveMarginInfo: '/api/margin/SaveMarginInfo',
      ApproveMarginOrders: '/api/margin/ApproveMarginOrder',
      RejectMarginOrders: '/api/margin/RejectMarginOrder',
      NoBidSymbolClientCount: '/api/margin/NoBidSymbolClientCount?filter=',
      NoBidSymbolClient: '/api/margin/NoBidSymbolClient',
      GetOrdersDayLimit: '/api/margin/GetOrdersDayLimit?filter=',
      GetClientsExposure: '/api/margin/GetClientsExposure?filter=',
      GetClientsGroupExposure: '/api/margin/GetClientsGroupExposure?filter=',
      GetAccounts: '/api/margin/GetAccounts',
      GetT1Widget: '/api/margin/GetT1Widget',
      SaveMarginCall: '/api/margin/SaveMarginCall',
      GetStockExposures: '/api/margin/GetStockExposures?filter=',
      GetMarginCategories: '/api/margin/GetMarginCategories',
      GetMarginCategory: '/api/margin/GetMarginCategory/',
      GetClientMarginCategories: '/api/margin/GetClientMarginCategories?filter=',
      GetStockLoosers: '/api/margin/GetStockLooserSummary',
      GetStockLoserExport: '/api/margin/GetStockLoserExport'
    },
    Settings: {
      GetSymbolTypes: '/api/Settings/ListSymbolType',
      AddSymbolType: '/api/Settings/SymbolType',
      DeleteSymbolType: '/api/Settings/DeleteSymbolType?Id=',
      GetMarkets: '/api/Settings/ListMarket',
      AddMarket: '/api/Settings/Market',
      DeleteMarket: '/api/Settings/DeleteMarket?Id=',
      GetNationalities: '/api/Settings/ListNationality',
      AddNationality: '/api/Settings/Nationality',
      DeleteNationality: '/api/Settings/DeleteNationality?Id=',
      GetCommissions: '/api/Settings/ListMasterCommision',
      AddCommission: '/api/Settings/CreateOrUpdateMasterCommision',
      DeleteCommission: '/api/Settings/DeleteMasterCommision?Id=',
      InsertOrUpdateMasterCommissionDetail: '/api/Settings/CreateOrUpdateCommissionDetails',
      DeleteCommissionDetails: '/api/Settings/DeleteCommissionDetails?GroupId=',
      PostCommissionDetails: '/api/Settings/PostCommission',
      GetCustodians: '/api/Settings/ListCustodian',
      AddCustodian: '/api/Settings/CreateOrUpdateCustodian',
      InsertOrUpdateCustodianCommissionDetail: '/api/Settings/CreateOrUpdateCustodianCommissionDetails',
      DeleteCustodian: '/api/Settings/DeleteCustodian?Id=',
      DeleteCustodianCommissionDetails: '/api/Settings/DeleteCustodianCommission?GroupId=',
      PostCustodianCommission: '/api/Settings/PostCustodianCommission',
      GetCustodianCommissionList: '/api/Settings/GetCustodianCommissionList?custodianCode=',
      GetCurrencies: '/api/Settings/ListCurrency',
      AddCurrency: '/api/Settings/Currency',
      DeleteCurrency: '/api/Settings/DeleteCurrency?Id=',
      GetClientTypeList: '/api/Settings/ListType',
      InsertClientTypeDetails: '/api/Settings/CreateOrUpdateType',
      DeleteClientType: '/api/Settings/DeleteClientType?Id=',
      GetBranchList: '/api/Settings/ListBranch',
      InsertBranchDetails: '/api/Settings/Branch',
      DeleteBranch: '/api/Settings/DeleteBranch?Id=',
      GetDepartmentList: '/api/Settings/ListDepartment',
      InsertDepartmentDetails: '/api/Settings/Department',
      DeleteDepartment: '/api/Settings/DeleteDepartment?Id=',
      GetJobList: '/api/Settings/ListJob',
      InsertJobDetails: '/api/Settings/Job',
      DeleteJob: '/api/Settings/DeleteJob?Id=',
      GetRoles: '/api/Settings/GetAllRoles',
      GetEmployeesByRoleID: '/api/Settings/GetEmployeesByRoleID?roleID=',
      GetAllModules: '/api/Settings/GetAllModules?roleID=',
      AddRole: '/api/Settings/Role',
      DeleteRole: '/api/Settings/DeleteRole?Id=',
      GetRolePrivileges: '/api/Settings/GetRolePrivileges?roleID=',
      GetEmployeePermission: '/api/Settings/ListEmployeePermissions',
      GetEmployees: '/api/Settings/GetAllEmployees',
      DeleteEmployee: '/api/Settings/DeleteEmployee?Id=',
      AddEmployee: '/api/Settings/AddEmployee',
      ResetEmployeeCredentials: '/api/Settings/ResetEmployeeCredentials',
      GetAppSubscribeList: '/api/Settings/ListAPPSubscribe',
      InsertOrUpdateAppSubscribeDetails: '/api/Settings/APPSubscribe',
      DeleteAppSubscribe: '/api/Settings/DeleteAPPSubscribe?Id=',
      GetAccountCategoryList: '/api/Settings/ListAccountCategory',
      InsertOrUpdateAccountCategoryDetails: '/api/Settings/CreateOrUpdateAccountCategory',
      DeleteAccountCategory: '/api/Settings/DeleteAccountCategory?Id=',
      GetMarketSettings: '/api/Settings/GetMarketSetting',
      PostMarketSettings: '/api/Settings/UpdateMarketSetting',
      GetGeneralSettings: '/api/Settings/GetGeneralSetting',
      UpdateGeneralSettings: '/api/Settings/UpdateGeneralSettings',
      GetActivityLog: '/api/Settings/GetActivityLog?request=',
      GetSubscriptionfees: '/api/Settings/Subscriptionfees?request=',
      GetTotlaSubscriptionfees: '/api/Settings/SubscriptionfeesTotal?request=',
      GetMasterDetailCommission: '/api/Settings/GetMasterDetailCommissionList?masterCommID=',
      SearchGLAccounts: '/api/Settings/SearchGLAccounts?searchQuery=',
      GetFinanceAccounts: '/api/Settings/GetFinanceAccounts',
      GetLisenceManagement: '/api/Settings/GetLisenceManagement',
      UpdateLisenceManagement: '/api/Settings/UpdateLisenceManagement',
      GetAllPageTypes: '/api/Settings/GetAllPageTypes',
      GetPageItemsByTypeID: '/api/Settings/GetPageItemsByTypeID?typeID=',
      InsertOrUpdatePageItem: '/api/Settings/InsertOrUpdatePageItem?request=',
      DeletePageItem: '/api/Settings/DeletePageItem?id=',
      GetPageTypeAttachments: '/api/Settings/GetPageTypeAttachments?typeID=',
      SearchSymbols: '/api/Settings/SearchSymbols?searchQuery=',
      GetSymbolByCode: '/api/Settings/GetSymbolByCode?symbolCode=',
      GetPageItemAttachment: '/api/Settings/GetPageItemAttachment?itemID=',
      DeleteItemAttachment: '/api/Settings/DeleteItemAttachment?id=',
      GetSMSMessages: '/api/Settings/GetSMSMessagesByFilter?filter=',
      ClearSMSMessage: '/api/Settings/ClearSMSMessage',
      ResendSMSMessage: '/api/Settings/ResendSMSMessage',
      GetEmailMessages: '/api/Settings/GetEmailMessagesByFilter?filter=',
      ClearEmailMessage: '/api/Settings/ClearEmailMessage',
      ResendEmailMessage: '/api/Settings/ResendEmailMessage',
      GetInvoiceDetails: '/api/Settings/GetInvoiceDetails?invoiceID=',
      GetBrokers: '/api/Settings/ListBroker',
      AddBroker: '/api/Settings/Broker',
      DeleteBroker: '/api/Settings/DeleteBroker?Id=',
      GetMarketList: '/api/Settings/GetMarketList',
      GetMarketWeekEnds: '/api/Settings/GetMarketWeekEnds',
      InsertOrUpdateWeekEnds: '/api/Settings/InsertOrUpdateWeekEnds',
      DeleteMarketWeekEnds: '/api/Settings/DeleteMarketWeekEnds?Id=',
      GetCalendar: '/api/Settings/GetCalendar',
      AddCalendar: '/api/Settings/AddCalendar',
      RemoveCalendar: '/api/Settings/RemoveCalendar?Id='
    },
    Suspensions:
    {
      AddjobRestriction: "/api/Client/CreateRestrictions",
      DeleteJobRestriction: "/api/Client/DeleteJobRestrictions?Id=",
      GetAllJobRestriction: "/api/Client/AllGetJobRestrictionsList?filter=",
      getJobRestrictionsList: '/api/Client/GetJobRestrictionsList?relationcode=',
    },
    Setting:
    {
      SettingApi: '/setting/getdata?request=',
      cityByGov: '/setting/getCitiesByGovId?govId=',
      getArchiveTypes: '/setting/GetArchiveTypes',
      GetComapnyMarginSettings: '/setting/GetComapnyMarginSettings?request=asd',
      createOrUpdateArchiveType: '/setting/CreateOrUpdateArchiveType',
      deleteArchiveType: '/setting/DeleteArchiveType?ID=',
      createSFTPDirectory: '/setting/CreateSFTPDirectory',
      deleteFile: '/sftp/DeleteFile?ArchivId=',
      uploadFile: '/sftp/UploadFile',
      downloadFile: '/sftp/downloadFile?ArchivId=',
      autoComplete: '/setting/AutoCompleteData?query='
    },
    Feed: {
      GetMarginSymbols: '/api/Feed/getMarginSymbols'
    }
  },

  validators: {
    regexLat:
      '^(\\+|-)?(?:90(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,20})?))$',
    regexLng:
      '^(\\+|-)?(?:180(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,20})?))$',
    phonePattern: '^([^A-Za-z])+$',
    emailPattern: '[a-zA-Z0-9.-_]{1,}@[a-zA-Z.-]{2,}[.]{1}[a-zA-Z]{2,}',
    numberOnly: '^[0-9]+$',
  },
  httpResponseStatusCode: {
    unknownError: 0,
    // Client error responses
    badRequest: 400,
    unauthorized: 401,
    paymentRequiredExperimental: 402,
    forbidden: 403,
    notFound: 404,
    methodNotAllowed: 405,
    notAcceptable: 406,
    proxyAuthenticationRequired: 407,
    requestTimeout: 408,
    conflict: 409,
    gone: 410,
    lengthRequired: 411,

    // Server error responses
    internalServerError: 500,
    notImplemented: 501,
    badGateway: 502,
    serviceUnavailable: 503,
    gatewayTimeout: 504,
    hTTPVersionNotSupported: 505,
    variantAlsoNegotiates: 506,
    insufficientStorage: 507,
    loopDetected: 508,
    notExtended: 510,
    networkAuthenticationRequired: 511,
  },

}

export const FormMode = {
  AddNew: "AddNew",
  AddNewSub: "newsubAccount",
  EditClient: "EditClient",
  View: "View"

}
